language: c

sudo: required

matrix:
  fast_finish: true

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - doxygen

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake ..
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd "${TRAVIS_BUILD_DIR}"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir build.fuzz && cd build.fuzz; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake .. -DENABLE_FUZZING=On -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++; fi

script:
  - cd "${TRAVIS_BUILD_DIR}/build"
  - cmake --build .
  - ctest --output-on-failure
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd "${TRAVIS_BUILD_DIR}/build.fuzz"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake --build . --target fuzz_check_all; fi

notifications:
  email:
    on_success: change
    on_failure: always

before_deploy:
  - npm install gitbook-cli -g
  - cd "${TRAVIS_BUILD_DIR}/docs"
  - "./make.sh"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: "docs/_book"
  keep-history: true
  on:
    branch: master
    condition: "$TRAVIS_OS_NAME" = "linux"
