language: c

sudo: false

matrix:
  fast_finish: true

os:
  - linux
  - osx

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake ..
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build.fuzz && cd build.fuzz
  - cmake .. -DENABLE_FUZZING=On -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

script:
  - cd "${TRAVIS_BUILD_DIR}/build"
  - cmake --build .
  - ctest --output-on-failure
  - cd "${TRAVIS_BUILD_DIR}/build.fuzz"
  - cmake --build . --target fuzz_check_all

notifications:
  email:
    on_success: change
    on_failure: always
