matrix:
  fast_finish: true

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      GENERATOR: "Visual Studio 12 Win64"
      CONFIG: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
      CONFIG: Release

before_build:
  - cmake -H. -Bbuild -G"%GENERATOR%"

build_script:
  - cmake --build build --config "%CONFIG%"
  - cmake --build build --target examples --config "%CONFIG%"
  - cmake --build build --target tools --config "%CONFIG%"

test_script:
  - cd build
  - ctest -C "%CONFIG%" --output-on-failure
