matrix:
  fast_finish: true

environment:
  matrix:
    - GENERATOR: "Visual Studio 12 Win64"
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release

    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Release

before_build:
  - cmake -H. -Bbuild -G"%GENERATOR%"

build_script:
  - cmake --build build --config "%CONFIG%"

test_script:
  - cd build
  - ctest -VV -C "%CONFIG%"
