name: Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.18.2'

    - name: Build
      run: cd docs && ./make.sh

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs/_book
